/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface Challenge {
  'startDay' : DayKey,
  'createdAt' : Timestamp,
  'target' : bigint,
}
export interface ChallengeProgress {
  'totalSold' : bigint,
  'perPlatform' : Array<[Platform, bigint]>,
  'percent' : bigint,
  'target' : bigint,
  'dayNumber' : bigint,
  'daysRemaining' : bigint,
  'currentStreak' : bigint,
  'milestones' : Array<Milestone>,
}
export type DayKey = bigint;
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Milestone {
  'title' : string,
  'unlocked' : boolean,
  'thresholdPercent' : bigint,
}
export type Platform = { 'shopee' : null } |
  { 'lazada' : null } |
  { 'tiktokShop' : null };
export interface QuizAnswerFeedback {
  'correctIndex' : bigint,
  'explanation' : string,
  'correct' : boolean,
  'questionId' : bigint,
  'chosenIndex' : bigint,
}
export interface QuizQuestionView {
  'id' : bigint,
  'prompt' : string,
  'options' : Array<string>,
}
export interface QuizResult {
  'day' : DayKey,
  'completedAt' : Timestamp,
  'total' : bigint,
  'score' : bigint,
  'points' : bigint,
}
export interface QuizSubmission {
  'day' : DayKey,
  'total' : bigint,
  'feedback' : Array<QuizAnswerFeedback>,
  'score' : bigint,
  'points' : bigint,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface SalesEntry {
  'day' : DayKey,
  'platform' : Platform,
  'updatedAt' : Timestamp,
  'quantity' : bigint,
}
export type Timestamp = bigint;
export type TipTheme = { 'listing' : null } |
  { 'layananPelanggan' : null } |
  { 'analisisData' : null } |
  { 'promosi' : null } |
  { 'konten' : null };
export interface TipView {
  'id' : bigint,
  'day' : DayKey,
  'theme' : TipTheme,
  'title' : string,
  'done' : boolean,
  'actionStep' : string,
  'platform' : Platform,
  'summary' : string,
  'favorite' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Add a tip to the caller's favorites.
   */
  'addFavorite' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Return the backend API documentation as Markdown.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Return the caller's challenge configuration.
   */
  'getChallenge' : ActorMethod<[], [] | [Challenge]>,
  /**
   * / Return the caller's aggregate challenge progress.
   */
  'getProgress' : ActorMethod<[], [] | [ChallengeProgress]>,
  /**
   * / Return the caller's quiz result for a given day, if played.
   */
  'getQuizResult' : ActorMethod<[DayKey], [] | [QuizResult]>,
  /**
   * / Return today's quiz questions (correct answers withheld).
   */
  'getTodayQuiz' : ActorMethod<[], Array<QuizQuestionView>>,
  /**
   * / Return the tip scheduled for today.
   */
  'getTodayTip' : ActorMethod<[], [] | [TipView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Return the caller's favorite tips.
   */
  'listFavorites' : ActorMethod<[], Array<TipView>>,
  /**
   * / Return the caller's quiz history, newest first.
   */
  'listQuizHistory' : ActorMethod<[], Array<QuizResult>>,
  /**
   * / Return the caller's sales history, newest first, optionally filtered by
   * / platform and an inclusive day range.
   */
  'listSales' : ActorMethod<
    [[] | [Platform], [] | [DayKey], [] | [DayKey]],
    Array<SalesEntry>
  >,
  /**
   * / Browse the tip archive, optionally filtered by day, platform, and theme.
   */
  'listTips' : ActorMethod<
    [[] | [DayKey], [] | [Platform], [] | [TipTheme]],
    Array<TipView>
  >,
  /**
   * / Mark a tip as done for the caller.
   */
  'markTipDone' : ActorMethod<[bigint], undefined>,
  /**
   * / Record or update the caller's sales for a day.
   */
  'recordSales' : ActorMethod<[DayKey, bigint, Platform], SalesEntry>,
  /**
   * / Remove a tip from the caller's favorites.
   */
  'removeFavorite' : ActorMethod<[bigint], undefined>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Start the caller's 100-day challenge.
   */
  'startChallenge' : ActorMethod<[bigint, DayKey], Challenge>,
  /**
   * / Submit the caller's answers for today's quiz.
   */
  'submitQuiz' : ActorMethod<[Array<[bigint, bigint]>], QuizSubmission>,
  /**
   * / Remove the caller's done mark from a tip.
   */
  'unmarkTipDone' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];