/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const DayKey = IDL.Nat;
export const Timestamp = IDL.Int;
export const Challenge = IDL.Record({
  'startDay' : DayKey,
  'createdAt' : Timestamp,
  'target' : IDL.Nat,
});
export const Platform = IDL.Variant({
  'shopee' : IDL.Null,
  'lazada' : IDL.Null,
  'tiktokShop' : IDL.Null,
});
export const Milestone = IDL.Record({
  'title' : IDL.Text,
  'unlocked' : IDL.Bool,
  'thresholdPercent' : IDL.Nat,
});
export const ChallengeProgress = IDL.Record({
  'totalSold' : IDL.Nat,
  'perPlatform' : IDL.Vec(IDL.Tuple(Platform, IDL.Nat)),
  'percent' : IDL.Nat,
  'target' : IDL.Nat,
  'dayNumber' : IDL.Nat,
  'daysRemaining' : IDL.Nat,
  'currentStreak' : IDL.Nat,
  'milestones' : IDL.Vec(Milestone),
});
export const QuizResult = IDL.Record({
  'day' : DayKey,
  'completedAt' : Timestamp,
  'total' : IDL.Nat,
  'score' : IDL.Nat,
  'points' : IDL.Nat,
});
export const QuizQuestionView = IDL.Record({
  'id' : IDL.Nat,
  'prompt' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const TipTheme = IDL.Variant({
  'listing' : IDL.Null,
  'layananPelanggan' : IDL.Null,
  'analisisData' : IDL.Null,
  'promosi' : IDL.Null,
  'konten' : IDL.Null,
});
export const TipView = IDL.Record({
  'id' : IDL.Nat,
  'day' : DayKey,
  'theme' : TipTheme,
  'title' : IDL.Text,
  'done' : IDL.Bool,
  'actionStep' : IDL.Text,
  'platform' : Platform,
  'summary' : IDL.Text,
  'favorite' : IDL.Bool,
});
export const SalesEntry = IDL.Record({
  'day' : DayKey,
  'platform' : Platform,
  'updatedAt' : Timestamp,
  'quantity' : IDL.Nat,
});
export const QuizAnswerFeedback = IDL.Record({
  'correctIndex' : IDL.Nat,
  'explanation' : IDL.Text,
  'correct' : IDL.Bool,
  'questionId' : IDL.Nat,
  'chosenIndex' : IDL.Nat,
});
export const QuizSubmission = IDL.Record({
  'day' : DayKey,
  'total' : IDL.Nat,
  'feedback' : IDL.Vec(QuizAnswerFeedback),
  'score' : IDL.Nat,
  'points' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addFavorite' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChallenge' : IDL.Func([], [IDL.Opt(Challenge)], ['query']),
  'getProgress' : IDL.Func([], [IDL.Opt(ChallengeProgress)], ['query']),
  'getQuizResult' : IDL.Func([DayKey], [IDL.Opt(QuizResult)], ['query']),
  'getTodayQuiz' : IDL.Func([], [IDL.Vec(QuizQuestionView)], ['query']),
  'getTodayTip' : IDL.Func([], [IDL.Opt(TipView)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listFavorites' : IDL.Func([], [IDL.Vec(TipView)], ['query']),
  'listQuizHistory' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
  'listSales' : IDL.Func(
      [IDL.Opt(Platform), IDL.Opt(DayKey), IDL.Opt(DayKey)],
      [IDL.Vec(SalesEntry)],
      ['query'],
    ),
  'listTips' : IDL.Func(
      [IDL.Opt(DayKey), IDL.Opt(Platform), IDL.Opt(TipTheme)],
      [IDL.Vec(TipView)],
      ['query'],
    ),
  'markTipDone' : IDL.Func([IDL.Nat], [], []),
  'recordSales' : IDL.Func([DayKey, IDL.Nat, Platform], [SalesEntry], []),
  'removeFavorite' : IDL.Func([IDL.Nat], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'startChallenge' : IDL.Func([IDL.Nat, DayKey], [Challenge], []),
  'submitQuiz' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      [QuizSubmission],
      [],
    ),
  'unmarkTipDone' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const DayKey = IDL.Nat;
  const Timestamp = IDL.Int;
  const Challenge = IDL.Record({
    'startDay' : DayKey,
    'createdAt' : Timestamp,
    'target' : IDL.Nat,
  });
  const Platform = IDL.Variant({
    'shopee' : IDL.Null,
    'lazada' : IDL.Null,
    'tiktokShop' : IDL.Null,
  });
  const Milestone = IDL.Record({
    'title' : IDL.Text,
    'unlocked' : IDL.Bool,
    'thresholdPercent' : IDL.Nat,
  });
  const ChallengeProgress = IDL.Record({
    'totalSold' : IDL.Nat,
    'perPlatform' : IDL.Vec(IDL.Tuple(Platform, IDL.Nat)),
    'percent' : IDL.Nat,
    'target' : IDL.Nat,
    'dayNumber' : IDL.Nat,
    'daysRemaining' : IDL.Nat,
    'currentStreak' : IDL.Nat,
    'milestones' : IDL.Vec(Milestone),
  });
  const QuizResult = IDL.Record({
    'day' : DayKey,
    'completedAt' : Timestamp,
    'total' : IDL.Nat,
    'score' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const QuizQuestionView = IDL.Record({
    'id' : IDL.Nat,
    'prompt' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const TipTheme = IDL.Variant({
    'listing' : IDL.Null,
    'layananPelanggan' : IDL.Null,
    'analisisData' : IDL.Null,
    'promosi' : IDL.Null,
    'konten' : IDL.Null,
  });
  const TipView = IDL.Record({
    'id' : IDL.Nat,
    'day' : DayKey,
    'theme' : TipTheme,
    'title' : IDL.Text,
    'done' : IDL.Bool,
    'actionStep' : IDL.Text,
    'platform' : Platform,
    'summary' : IDL.Text,
    'favorite' : IDL.Bool,
  });
  const SalesEntry = IDL.Record({
    'day' : DayKey,
    'platform' : Platform,
    'updatedAt' : Timestamp,
    'quantity' : IDL.Nat,
  });
  const QuizAnswerFeedback = IDL.Record({
    'correctIndex' : IDL.Nat,
    'explanation' : IDL.Text,
    'correct' : IDL.Bool,
    'questionId' : IDL.Nat,
    'chosenIndex' : IDL.Nat,
  });
  const QuizSubmission = IDL.Record({
    'day' : DayKey,
    'total' : IDL.Nat,
    'feedback' : IDL.Vec(QuizAnswerFeedback),
    'score' : IDL.Nat,
    'points' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addFavorite' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChallenge' : IDL.Func([], [IDL.Opt(Challenge)], ['query']),
    'getProgress' : IDL.Func([], [IDL.Opt(ChallengeProgress)], ['query']),
    'getQuizResult' : IDL.Func([DayKey], [IDL.Opt(QuizResult)], ['query']),
    'getTodayQuiz' : IDL.Func([], [IDL.Vec(QuizQuestionView)], ['query']),
    'getTodayTip' : IDL.Func([], [IDL.Opt(TipView)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listFavorites' : IDL.Func([], [IDL.Vec(TipView)], ['query']),
    'listQuizHistory' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
    'listSales' : IDL.Func(
        [IDL.Opt(Platform), IDL.Opt(DayKey), IDL.Opt(DayKey)],
        [IDL.Vec(SalesEntry)],
        ['query'],
      ),
    'listTips' : IDL.Func(
        [IDL.Opt(DayKey), IDL.Opt(Platform), IDL.Opt(TipTheme)],
        [IDL.Vec(TipView)],
        ['query'],
      ),
    'markTipDone' : IDL.Func([IDL.Nat], [], []),
    'recordSales' : IDL.Func([DayKey, IDL.Nat, Platform], [SalesEntry], []),
    'removeFavorite' : IDL.Func([IDL.Nat], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'startChallenge' : IDL.Func([IDL.Nat, DayKey], [Challenge], []),
    'submitQuiz' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        [QuizSubmission],
        [],
      ),
    'unmarkTipDone' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };