/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Cell {
    value: Value;
    name: string;
}
export interface Challenge {
    startDay: DayKey;
    createdAt: Timestamp;
    target: bigint;
}
export interface ChallengeProgress {
    totalSold: bigint;
    perPlatform: Array<[Platform, bigint]>;
    percent: bigint;
    target: bigint;
    dayNumber: bigint;
    daysRemaining: bigint;
    currentStreak: bigint;
    milestones: Array<Milestone>;
}
export type DayKey = bigint;
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Milestone {
    title: string;
    unlocked: boolean;
    thresholdPercent: bigint;
}
export interface QuizAnswerFeedback {
    correctIndex: bigint;
    explanation: string;
    correct: boolean;
    questionId: bigint;
    chosenIndex: bigint;
}
export interface QuizQuestionView {
    id: bigint;
    prompt: string;
    options: Array<string>;
}
export interface QuizResult {
    day: DayKey;
    completedAt: Timestamp;
    total: bigint;
    score: bigint;
    points: bigint;
}
export interface QuizSubmission {
    day: DayKey;
    total: bigint;
    feedback: Array<QuizAnswerFeedback>;
    score: bigint;
    points: bigint;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface SalesEntry {
    day: DayKey;
    platform: Platform;
    updatedAt: Timestamp;
    quantity: bigint;
}
export type Timestamp = bigint;
export interface TipView {
    id: bigint;
    day: DayKey;
    theme: TipTheme;
    title: string;
    done: boolean;
    actionStep: string;
    platform: Platform;
    summary: string;
    favorite: boolean;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum Platform {
    shopee = "shopee",
    lazada = "lazada",
    tiktokShop = "tiktokShop"
}
export enum TipTheme {
    listing = "listing",
    layananPelanggan = "layananPelanggan",
    analisisData = "analisisData",
    promosi = "promosi",
    konten = "konten"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    /**
     * / Add a tip to the caller's favorites.
     */
    addFavorite(tipId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    execute(qJson: string): Promise<Result>;
    /**
     * / Return the backend API documentation as Markdown.
     */
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Return the caller's challenge configuration.
     */
    getChallenge(): Promise<Challenge | null>;
    /**
     * / Return the caller's aggregate challenge progress.
     */
    getProgress(): Promise<ChallengeProgress | null>;
    /**
     * / Return the caller's quiz result for a given day, if played.
     */
    getQuizResult(day: DayKey): Promise<QuizResult | null>;
    /**
     * / Return today's quiz questions (correct answers withheld).
     */
    getTodayQuiz(): Promise<Array<QuizQuestionView>>;
    /**
     * / Return the tip scheduled for today.
     */
    getTodayTip(): Promise<TipView | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Return the caller's favorite tips.
     */
    listFavorites(): Promise<Array<TipView>>;
    /**
     * / Return the caller's quiz history, newest first.
     */
    listQuizHistory(): Promise<Array<QuizResult>>;
    /**
     * / Return the caller's sales history, newest first, optionally filtered by
     * / platform and an inclusive day range.
     */
    listSales(platform: Platform | null, fromDay: DayKey | null, toDay: DayKey | null): Promise<Array<SalesEntry>>;
    /**
     * / Browse the tip archive, optionally filtered by day, platform, and theme.
     */
    listTips(day: DayKey | null, platform: Platform | null, theme: TipTheme | null): Promise<Array<TipView>>;
    /**
     * / Mark a tip as done for the caller.
     */
    markTipDone(tipId: bigint): Promise<void>;
    /**
     * / Record or update the caller's sales for a day.
     */
    recordSales(day: DayKey, quantity: bigint, platform: Platform): Promise<SalesEntry>;
    /**
     * / Remove a tip from the caller's favorites.
     */
    removeFavorite(tipId: bigint): Promise<void>;
    schema(): Promise<string>;
    /**
     * / Start the caller's 100-day challenge.
     */
    startChallenge(target: bigint, startDay: DayKey): Promise<Challenge>;
    /**
     * / Submit the caller's answers for today's quiz.
     */
    submitQuiz(answers: Array<[bigint, bigint]>): Promise<QuizSubmission>;
    /**
     * / Remove the caller's done mark from a tip.
     */
    unmarkTipDone(tipId: bigint): Promise<void>;
}
import type { Cell as _Cell, Challenge as _Challenge, ChallengeProgress as _ChallengeProgress, DayKey as _DayKey, Error as _Error, Milestone as _Milestone, Platform as _Platform, QuizResult as _QuizResult, Result as _Result, Result__1 as _Result__1, SalesEntry as _SalesEntry, Timestamp as _Timestamp, TipTheme as _TipTheme, TipView as _TipView, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addFavorite(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavorite(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChallenge(): Promise<Challenge | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChallenge();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChallenge();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgress(): Promise<ChallengeProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgress();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgress();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizResult(arg0: DayKey): Promise<QuizResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizResult(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizResult(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodayQuiz(): Promise<Array<QuizQuestionView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayQuiz();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayQuiz();
            return result;
        }
    }
    async getTodayTip(): Promise<TipView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayTip();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayTip();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listFavorites(): Promise<Array<TipView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFavorites();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFavorites();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async listQuizHistory(): Promise<Array<QuizResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.listQuizHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listQuizHistory();
            return result;
        }
    }
    async listSales(arg0: Platform | null, arg1: DayKey | null, arg2: DayKey | null): Promise<Array<SalesEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSales(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n30(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n30(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSales(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n30(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n30(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTips(arg0: DayKey | null, arg1: Platform | null, arg2: TipTheme | null): Promise<Array<TipView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTips(to_candid_opt_n30(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTips(to_candid_opt_n30(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async markTipDone(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markTipDone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markTipDone(arg0);
            return result;
        }
    }
    async recordSales(arg0: DayKey, arg1: bigint, arg2: Platform): Promise<SalesEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSales(arg0, arg1, to_candid_Platform_n29(this._uploadFile, this._downloadFile, arg2));
                return from_candid_SalesEntry_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSales(arg0, arg1, to_candid_Platform_n29(this._uploadFile, this._downloadFile, arg2));
            return from_candid_SalesEntry_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFavorite(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFavorite(arg0);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async startChallenge(arg0: bigint, arg1: DayKey): Promise<Challenge> {
        if (this.processError) {
            try {
                const result = await this.actor.startChallenge(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startChallenge(arg0, arg1);
            return result;
        }
    }
    async submitQuiz(arg0: Array<[bigint, bigint]>): Promise<QuizSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuiz(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuiz(arg0);
            return result;
        }
    }
    async unmarkTipDone(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unmarkTipDone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unmarkTipDone(arg0);
            return result;
        }
    }
}
function from_candid_Cell_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_ChallengeProgress_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChallengeProgress): ChallengeProgress {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Platform_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Platform): Platform {
    return "shopee" in value ? Platform.shopee : "lazada" in value ? Platform.lazada : "tiktokShop" in value ? Platform.tiktokShop : value;
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_SalesEntry_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SalesEntry): SalesEntry {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_TipTheme_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TipTheme): TipTheme {
    return "listing" in value ? TipTheme.listing : "layananPelanggan" in value ? TipTheme.layananPelanggan : "analisisData" in value ? TipTheme.analisisData : "promosi" in value ? TipTheme.promosi : "konten" in value ? TipTheme.konten : value;
}
function from_candid_TipView_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TipView): TipView {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Challenge]): Challenge | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChallengeProgress]): ChallengeProgress | null {
    return value.length === 0 ? null : from_candid_ChallengeProgress_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuizResult]): QuizResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TipView]): TipView | null {
    return value.length === 0 ? null : from_candid_TipView_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n12(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalSold: bigint;
    perPlatform: Array<[_Platform, bigint]>;
    percent: bigint;
    target: bigint;
    dayNumber: bigint;
    daysRemaining: bigint;
    currentStreak: bigint;
    milestones: Array<_Milestone>;
}): {
    totalSold: bigint;
    perPlatform: Array<[Platform, bigint]>;
    percent: bigint;
    target: bigint;
    dayNumber: bigint;
    daysRemaining: bigint;
    currentStreak: bigint;
    milestones: Array<Milestone>;
} {
    return {
        totalSold: value.totalSold,
        perPlatform: from_candid_vec_n19(_uploadFile, _downloadFile, value.perPlatform),
        percent: value.percent,
        target: value.target,
        dayNumber: value.dayNumber,
        daysRemaining: value.daysRemaining,
        currentStreak: value.currentStreak,
        milestones: value.milestones
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    day: _DayKey;
    theme: _TipTheme;
    title: string;
    done: boolean;
    actionStep: string;
    platform: _Platform;
    summary: string;
    favorite: boolean;
}): {
    id: bigint;
    day: DayKey;
    theme: TipTheme;
    title: string;
    done: boolean;
    actionStep: string;
    platform: Platform;
    summary: string;
    favorite: boolean;
} {
    return {
        id: value.id,
        day: value.day,
        theme: from_candid_TipTheme_n26(_uploadFile, _downloadFile, value.theme),
        title: value.title,
        done: value.done,
        actionStep: value.actionStep,
        platform: from_candid_Platform_n21(_uploadFile, _downloadFile, value.platform),
        summary: value.summary,
        favorite: value.favorite
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: _DayKey;
    platform: _Platform;
    updatedAt: _Timestamp;
    quantity: bigint;
}): {
    day: DayKey;
    platform: Platform;
    updatedAt: Timestamp;
    quantity: bigint;
} {
    return {
        day: value.day,
        platform: from_candid_Platform_n21(_uploadFile, _downloadFile, value.platform),
        updatedAt: value.updatedAt,
        quantity: value.quantity
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n8(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_tuple_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Platform, bigint]): [Platform, bigint] {
    return [
        from_candid_Platform_n21(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Platform, bigint]>): Array<[Platform, bigint]> {
    return value.map((x)=>from_candid_tuple_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TipView>): Array<TipView> {
    return value.map((x)=>from_candid_TipView_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SalesEntry>): Array<SalesEntry> {
    return value.map((x)=>from_candid_SalesEntry_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Platform_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Platform): _Platform {
    return value == Platform.shopee ? {
        shopee: null
    } : value == Platform.lazada ? {
        lazada: null
    } : value == Platform.tiktokShop ? {
        tiktokShop: null
    } : value;
}
function to_candid_TipTheme_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TipTheme): _TipTheme {
    return value == TipTheme.listing ? {
        listing: null
    } : value == TipTheme.layananPelanggan ? {
        layananPelanggan: null
    } : value == TipTheme.analisisData ? {
        analisisData: null
    } : value == TipTheme.promosi ? {
        promosi: null
    } : value == TipTheme.konten ? {
        konten: null
    } : value;
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Platform | null): [] | [_Platform] {
    return value === null ? candid_none() : candid_some(to_candid_Platform_n29(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayKey | null): [] | [_DayKey] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TipTheme | null): [] | [_TipTheme] {
    return value === null ? candid_none() : candid_some(to_candid_TipTheme_n35(_uploadFile, _downloadFile, value));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
